### ISSUE TITLE
Looks good 👍 

### ISSUE THREAD

**Issue by DLND8** [MirjamNoetzli/cma-week2#1]
Just had a look at your code. It looks good, great job!

Just one small thing. It is best practice to use the "" when you load libraries. e.g. `library("ggplot2")` .
https://github.com/MirjamNoetzli/cma-week2/blob/54e9130f9e657ad7cd0e1b8952e31ea3af2ca3e6/Exercise2.Rmd#L12

**Comment by MirjamNoetzli** [comment]
Thank you for your feedback Dominic!
________________________________
Von: Dominic ***@***.***>
Gesendet: Dienstag, 9. Mai 2023 11:41
An: MirjamNoetzli/cma-week2 ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [MirjamNoetzli/cma-week2] Looks good 👍 (Issue #1)


Just had a look at your code. It looks good, great job!

Just one small thing. It is best practice to use the "" when you load libraries. e.g. library("ggplot2") .
https://github.com/MirjamNoetzli/cma-week2/blob/54e9130f9e657ad7cd0e1b8952e31ea3af2ca3e6/Exercise2.Rmd#L12
